name: Pull request testing

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test_pr:
    if: github.event.pull_request.draft == false
    name: 'Testing pull request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap the project
        run: npm run bootstrap
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test