# This action is a copy of `release-wc-and-playground` workflow for the purpose of the` next` branch only. 
name: Release Web-component

on: 
  release:
    branches:
      - next
    types: 
      - published

jobs:

  webcomponent:
    name: Release Web-component
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: next
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install latest version of library in the web-component
        run: VERSION=${{github.event.release.tag_name}} npm run install:reactcomp
        working-directory: ./web-component
      - name: Install dependencies
        run: npm install
      - name: Bump version in package.json
        # There is no need to substract "v" from the tag as version script handles it
        # When adding "bump:version" script in package.json, make sure no tags are added by default (--no-git-tag-version) as they are already added by release workflow
        # When adding "bump:version" script in package.json, make sure --allow-same-version is set in case someone forgot and updated package.json manually and we want to avoide this action to fail and raise confusion
        run: VERSION=${{github.event.release.tag_name}} npm run bump:webcomp:version
      - name: Release web-component to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./web-component/package.json
          access: public
