name: Simple PR Validation

on:
  pull_request
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm install
      - name: Bootstrap the project
        run: npm run bootstrap
      - name: Run library tests
        run: npm test